version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: bookshelf:latest
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      VITE_API_URL: http://backend:8080
    ports:
      - "8080:8080"
      - "5173:5173"