#Backend
FROM openjdk:17-jdk-alpine AS backend-build
WORKDIR /app/backend
COPY src ./src
COPY build.gradle .
COPY settings.gradle .
COPY gradlew ./
COPY gradle/wrapper/gradle-wrapper.jar ./gradle/wrapper/
COPY gradle/wrapper/gradle-wrapper.properties ./gradle/wrapper/
RUN chmod +x gradlew
RUN ./gradlew build


FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY --from=backend-build /app/backend/build/libs/Bookshelf-*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]